# Generated by Django 4.2.21 on 2025-05-15 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_directory_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directory',
            name='user',
        ),
    ]
